### ISSUE TITLE
Waypoints property has different names in XMI (wayPoints) and XSD (waypoint)

### ISSUE THREAD

**Issue by philippfromme** [omg-dmn-taskforce/omg-dmn-spec#11]
The waypoints property has different names in the [XMI](https://github.com/omg-dmn-taskforce/omg-dmn-spec/blob/master/xmi/DMNDI13.xmi#L452) and the [XSD](https://github.com/omg-dmn-taskforce/omg-dmn-spec/blob/master/xsd/DI.xsd#L88).

In the XMI its name is `wayPoints` and in the XSD it's `waypoint`. Shouldn't they be the same?

**Comment by falko** [comment]
I just double-checked with BPMN: We should rename `wayPoints` to `wayPoint` in the meta model.

**Comment by falko** [comment]
Even the original DI meta model calls it `waypoint`:

![image](https://user-images.githubusercontent.com/40038/218502644-0b00f3e9-76dc-4361-94ba-fa8d737ae734.png)

**Comment by falko** [comment]
This could be added to https://issues.omg.org/browse/DMN15-148
