### ISSUE TITLE
Typo in Context#contextEntry

### ISSUE THREAD

**Issue by philippfromme** [omg-dmn-taskforce/omg-dmn-spec#12]
There is a typo in the `contextEntry` property of `dmn:Context`:

```xml
<packagedElement xmi:type="uml:Class" name="Context" ...>
  ...
  <ownedAttribute xmi:type="uml:Property" name="contextEnrty"...>
    ...
  </ownedAttribute>
</packagedElement>
```

See https://github.com/omg-dmn-taskforce/omg-dmn-spec/tree/v1.3/xmi/DMN13.xmi#L1533

**Comment by falko** [comment]
Proposal: Rename `contextEnrty` to `contextEntry` in the UML metamodel.

**Comment by falko** [comment]
This could be added to https://issues.omg.org/browse/DMN15-148
